# Generated by Django 4.1.7 on 2023-03-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Permission', models.TextField()),
            ],
            options={
                'permissions': (('SystemAdmin', 'SystemAdmin'), ('SystemUser', 'SystemUser'), ('SystemGuest', 'SystemGuest'), ('AddPermissions', 'AddPermissions'), ('Database', 'Database')),
            },
        ),
    ]
