# Generated by Django 4.1.7 on 2023-03-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings_fieldnames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Veld1', models.CharField(max_length=15)),
                ('Veld2', models.CharField(max_length=15)),
                ('Veld3', models.CharField(max_length=15)),
                ('Veld4', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Settings Field Names',
            },
        ),
    ]
