# Generated by Django 4.1.7 on 2023-03-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_settings_fieldnames'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lights_fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Veld1', models.CharField(max_length=10)),
                ('Veld2', models.CharField(max_length=10)),
                ('Veld3', models.CharField(max_length=10)),
                ('Veld4', models.CharField(max_length=10)),
                ('Veld5', models.CharField(max_length=10)),
                ('Veld6', models.CharField(max_length=10)),
                ('Veld7', models.CharField(max_length=10)),
                ('Veld8', models.CharField(max_length=10)),
                ('Veld9', models.CharField(max_length=10)),
                ('Veld10', models.CharField(max_length=10)),
                ('Veld11', models.CharField(max_length=10)),
                ('Veld12', models.CharField(max_length=10)),
                ('Veld13', models.CharField(max_length=10)),
                ('Veld14', models.CharField(max_length=10)),
                ('Veld15', models.CharField(max_length=10)),
                ('Veld16', models.CharField(max_length=10)),
                ('Veld17', models.CharField(max_length=10)),
                ('Veld18', models.CharField(max_length=10)),
                ('Veld19', models.CharField(max_length=10)),
                ('Veld20', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Lights fields',
            },
        ),
        migrations.AlterField(
            model_name='settings_fieldnames',
            name='Veld1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='settings_fieldnames',
            name='Veld2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='settings_fieldnames',
            name='Veld3',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='settings_fieldnames',
            name='Veld4',
            field=models.CharField(max_length=10),
        ),
    ]
