# Generated by Django 4.1.7 on 2023-03-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_lights_fields_alter_settings_fieldnames_veld1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lights_fields',
            old_name='Veld1',
            new_name='Lamp1',
        ),
        migrations.RenameField(
            model_name='lights_fields',
            old_name='Veld10',
            new_name='Lamp10',
        ),
        migrations.RenameField(
            model_name='lights_fields',
            old_name='Veld11',
            new_name='Lamp11',
        ),
        migrations.RenameField(
            model_name='lights_fields',
            old_name='Veld12',
            new_name='Lamp12',
        ),
        migrations.RenameField(
            model_name='lights_fields',
            old_name='Veld13',
            new_name='Lamp13',
        ),
        migrations.RenameField(
            model_name='lights_fields',
            old_name='Veld14',
            new_name='Lamp14',
        ),
        migrations.RenameField(
            model_name='lights_fields',
            old_name='Veld15',
            new_name='Lamp15',
        ),
        migrations.RenameField(
            model_name='lights_fields',
            old_name='Veld16',
            new_name='Lamp16',
        ),
        migrations.RenameField(
            model_name='lights_fields',
            old_name='Veld17',
            new_name='Lamp17',
        ),
        migrations.RenameField(
            model_name='lights_fields',
            old_name='Veld18',
            new_name='Lamp18',
        ),
        migrations.RenameField(
            model_name='lights_fields',
            old_name='Veld19',
            new_name='Lamp19',
        ),
        migrations.RenameField(
            model_name='lights_fields',
            old_name='Veld2',
            new_name='Lamp2',
        ),
        migrations.RenameField(
            model_name='lights_fields',
            old_name='Veld20',
            new_name='Lamp20',
        ),
        migrations.RenameField(
            model_name='lights_fields',
            old_name='Veld3',
            new_name='Lamp3',
        ),
        migrations.RenameField(
            model_name='lights_fields',
            old_name='Veld4',
            new_name='Lamp4',
        ),
        migrations.RenameField(
            model_name='lights_fields',
            old_name='Veld5',
            new_name='Lamp5',
        ),
        migrations.RenameField(
            model_name='lights_fields',
            old_name='Veld6',
            new_name='Lamp6',
        ),
        migrations.RenameField(
            model_name='lights_fields',
            old_name='Veld7',
            new_name='Lamp7',
        ),
        migrations.RenameField(
            model_name='lights_fields',
            old_name='Veld8',
            new_name='Lamp8',
        ),
        migrations.RenameField(
            model_name='lights_fields',
            old_name='Veld9',
            new_name='Lamp9',
        ),
    ]
