# Generated by Django 4.1.7 on 2023-03-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_rename_veld1_lights_fields_lamp1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lights_fields',
            new_name='Settings_lightnames',
        ),
    ]
