# Generated by Django 4.1.7 on 2023-03-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_rename_lights_fields_settings_lightnames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings_lightnames',
            name='Lamp10',
        ),
        migrations.RemoveField(
            model_name='settings_lightnames',
            name='Lamp11',
        ),
        migrations.RemoveField(
            model_name='settings_lightnames',
            name='Lamp12',
        ),
        migrations.RemoveField(
            model_name='settings_lightnames',
            name='Lamp13',
        ),
        migrations.RemoveField(
            model_name='settings_lightnames',
            name='Lamp14',
        ),
        migrations.RemoveField(
            model_name='settings_lightnames',
            name='Lamp15',
        ),
        migrations.RemoveField(
            model_name='settings_lightnames',
            name='Lamp16',
        ),
        migrations.RemoveField(
            model_name='settings_lightnames',
            name='Lamp17',
        ),
        migrations.RemoveField(
            model_name='settings_lightnames',
            name='Lamp18',
        ),
        migrations.RemoveField(
            model_name='settings_lightnames',
            name='Lamp19',
        ),
        migrations.RemoveField(
            model_name='settings_lightnames',
            name='Lamp20',
        ),
        migrations.RemoveField(
            model_name='settings_lightnames',
            name='Lamp7',
        ),
        migrations.RemoveField(
            model_name='settings_lightnames',
            name='Lamp8',
        ),
        migrations.RemoveField(
            model_name='settings_lightnames',
            name='Lamp9',
        ),
        migrations.AddField(
            model_name='settings_lightnames',
            name='field_id',
            field=models.CharField(default='VID-A', max_length=5),
            preserve_default=False,
        ),
    ]
