# Generated by Django 4.1.7 on 2023-03-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_remove_settings_lightnames_lamp10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selecting_fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Fields',
            },
        ),
        migrations.AlterField(
            model_name='settings_lightnames',
            name='field_id',
            field=models.CharField(max_length=50),
        ),
    ]
