# Generated by Django 4.1.7 on 2023-03-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_selecting_fields_field1_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selecting_buttons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lamp001_bool', models.BooleanField(default=False)),
                ('Lamp002_bool', models.BooleanField(default=False)),
                ('Lamp003_bool', models.BooleanField(default=False)),
                ('lamp004_bool', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='selecting_fields',
            options={},
        ),
        migrations.RemoveField(
            model_name='selecting_fields',
            name='field_id',
        ),
    ]
