# Generated by Django 4.1.7 on 2023-03-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_selecting_buttons_alter_selecting_fields_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lamp001_bool', models.BooleanField(default=False)),
                ('Lamp002_bool', models.BooleanField(default=False)),
                ('Lamp003_bool', models.BooleanField(default=False)),
                ('lamp004_bool', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Selecting_buttons',
        ),
    ]
