# Generated by Django 4.1.7 on 2023-03-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_lightbutton_delete_selecting_buttons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightbutton',
            name='lamp004_bool',
        ),
        migrations.AddField(
            model_name='lightbutton',
            name='Lamp0010_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lightbutton',
            name='Lamp0011_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lightbutton',
            name='Lamp0012_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lightbutton',
            name='Lamp0013_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lightbutton',
            name='Lamp0014_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lightbutton',
            name='Lamp0015_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lightbutton',
            name='Lamp0016_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lightbutton',
            name='Lamp005_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lightbutton',
            name='Lamp006_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lightbutton',
            name='Lamp007_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lightbutton',
            name='Lamp008_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lightbutton',
            name='Lamp009_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lightbutton',
            name='Lamp004_bool',
            field=models.BooleanField(default=False),
        ),
    ]
