# Generated by Django 4.1.7 on 2023-03-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_remove_lightbutton_lamp004_bool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecting_fields',
            name='field10_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selecting_fields',
            name='field11_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selecting_fields',
            name='field12_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selecting_fields',
            name='field13_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selecting_fields',
            name='field14_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selecting_fields',
            name='field15_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selecting_fields',
            name='field16_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selecting_fields',
            name='field17_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selecting_fields',
            name='field18_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selecting_fields',
            name='field19_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selecting_fields',
            name='field20_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selecting_fields',
            name='field21_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selecting_fields',
            name='field22_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selecting_fields',
            name='field23_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selecting_fields',
            name='field24_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selecting_fields',
            name='field7_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selecting_fields',
            name='field8_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selecting_fields',
            name='field9_active',
            field=models.BooleanField(default=False),
        ),
    ]
