# Generated by Django 4.1.7 on 2023-03-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_selecting_fields_field10_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='IMG/')),
            ],
        ),
        migrations.DeleteModel(
            name='Settings_lightnames',
        ),
    ]
